name: 'telegram_dbt'
version: '1.0.0'
config-version: 2

profile: 'telegram_profile'  # This should match your profile name in profiles.yml

model-paths: ['models']
seed-paths: ['seeds']
macro-paths: ['macros']
target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_modules'

models:
  telegram_dbt:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
    enrichment:
      +materialized: table
