name: telegram_dbt
version: '1.0'
config-version: 2

profile: telegram_dbt_profile  

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  telegram_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
    enrichment:
      +materialized: table

